apiVersion: k8s.nginx.org/v1alpha1
kind: NginxIngressController
metadata:
  name: my-nginx-ingress-controller
  namespace: my-nginx-ingress
spec:
  type: deployment
  nginxPlus: false
  image:
    repository: registry.hub.docker.com/nginx/nginx-ingress
    tag: edge-ubi
    pullPolicy: Always
  replicas: 1
  serviceType: NodePort
  